SET ECHO ON 
SET FEEDBACK ON 
WHENEVER SQLERROR EXIT SQL.SQLCODE 
DELETE FROM SESSIONS; 
DELETE FROM HTE_REVIEWS; 
DELETE FROM REVIEWS; 
DELETE FROM GROUP_MEMBERS; 
DELETE FROM MENTOR_SKILL; 
DELETE FROM AVAILABILITY; 
DELETE FROM SKILLS; 
DELETE FROM GROUPS; 
DELETE FROM MENTOR; 
DELETE FROM USER_PROFILES; 
DELETE FROM AUTH_USERS; 
COMMIT; 
EXIT; 
