SET ECHO ON 
SET FEEDBACK ON 
WHENEVER SQLERROR EXIT SQL.SQLCODE 
SELECT table_name FROM user_tables WHERE table_name IN ('SESSIONS','AUTH_USERS','GROUP_MEMBERS','GROUPS','REVIEWS','USER_PROFILES','SKILLS','AVAILABILITY','MENTOR','MENTOR_SKILL','HTE_REVIEWS'); 
EXIT; 
