spring.application.name=Session-Service

server.port=9090

spring.datasource.driverClassName=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//oracle-db:1521/XEPDB1
spring.datasource.username=system
spring.datasource.password=oracle

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true