spring.application.name=Session-Service

server.port=9090

spring.datasource.driverClassName=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//host.docker.internal:1521/xe
spring.datasource.username=scott
spring.datasource.password=tiger

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true